# Generated by Django 4.0 on 2022-01-24 09:20

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='заголовок')),
                ('published', models.DateField(default=datetime.datetime.now, verbose_name='опубликовано')),
                ('description', ckeditor.fields.RichTextField(verbose_name='текст новости')),
                ('is_active', models.BooleanField(default=True, verbose_name='новость активна')),
                ('likes', models.PositiveSmallIntegerField(default=0, verbose_name='лайки')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, verbose_name='тэг')),
                ('slug', models.SlugField(max_length=80, verbose_name='path url')),
            ],
            options={
                'verbose_name_plural': 'Тэги новостей',
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название видео')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата')),
                ('video_url', models.URLField(verbose_name='ссылка на видео')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Видео youtube',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата комментария')),
                ('comment_text', models.TextField(verbose_name='текст комментария')),
                ('failed_moderation', models.TextField(blank=True, verbose_name='комментарий админа портала в случае непрохождения модерации')),
                ('is_active', models.BooleanField(default=False, verbose_name='комментарий активен')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='комментарий к новости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь комментария')),
            ],
            options={
                'verbose_name_plural': 'Комментарии к новостям',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='main.Tags', verbose_name='тэги'),
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='news', verbose_name='фото новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_news', to='main.news')),
            ],
        ),
    ]
