# Generated by Django 4.0 on 2022-08-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['tag_name'], 'verbose_name_plural': 'Тэги новостей'},
        ),
        migrations.AlterField(
            model_name='imagenews',
            name='img',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='news', verbose_name='фото новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='заголовок'),
        ),
    ]
