# Generated by Django 4.0 on 2022-09-29 06:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_property_mid_rating'),
        ('main', '0003_alter_news_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок мероприятия')),
                ('start_date', models.DateField(verbose_name='начало мероприятия')),
                ('finish_date', models.DateField(verbose_name='конец мероприятия')),
                ('description', ckeditor.fields.RichTextField(verbose_name='текст мероприятия')),
                ('event_img', models.ImageField(max_length=256, upload_to='events', verbose_name='фото меропритятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='мероприятие активно')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city', verbose_name='город')),
            ],
            options={
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-start_date'],
            },
        ),
    ]
