# Generated by Django 4.0 on 2022-10-02 06:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='текст')),
            ],
            options={
                'verbose_name_plural': 'Политика сайта',
            },
        ),
    ]
