# Generated by Django 4.0 on 2022-10-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_visit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='просмотры новости'),
        ),
    ]
