# Generated by Django 4.0 on 2022-10-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_persondatatreatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondatatreatment',
            old_name='text',
            new_name='text_field',
        ),
    ]
