# Generated by Django 4.0 on 2022-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_text_persondatatreatment_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='descr',
            field=models.CharField(blank=True, max_length=300, verbose_name='описание для мета тэгов'),
        ),
        migrations.AddField(
            model_name='events',
            name='key_words',
            field=models.CharField(blank=True, max_length=256, verbose_name='ключевые слова для мета тэгов'),
        ),
        migrations.AddField(
            model_name='news',
            name='descr',
            field=models.CharField(blank=True, max_length=256, verbose_name='описание для мета тэгов'),
        ),
    ]
