# Generated by Django 4.0 on 2022-08-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('property', '0015_alter_property_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='избранный ЖК')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Избранные новостройки',
            },
        ),
        migrations.CreateModel(
            name='FavoritesFlats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.flats', verbose_name='избранная квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_flats', to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Избранные квартиры',
            },
        ),
    ]
