# Generated by Django 4.0 on 2022-01-24 09:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название ЖК')),
                ('build_stage', models.CharField(choices=[('b', 'строится'), ('p', 'сдан'), ('d', 'долгострой')], default='b', max_length=10, verbose_name='Стадия строительства')),
                ('slug', models.SlugField(verbose_name='поле url')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание объекта')),
                ('addr', models.CharField(max_length=256, verbose_name='Адрес')),
                ('small_img', models.ImageField(upload_to=property.models.img_path_small, verbose_name='уменьшенное фото')),
                ('main_contractor', models.CharField(max_length=64, verbose_name='Застройщик')),
                ('building_company', models.CharField(blank=True, max_length=128, verbose_name='Подрядчик')),
                ('pr_declaration', models.CharField(max_length=128, verbose_name='Проектная декларация')),
                ('pr_decl_link', models.URLField(verbose_name='Ссылка на проектную декларацию')),
                ('operation_term', models.CharField(max_length=32, verbose_name='Ввод в эксплуатацию')),
                ('send_keys', models.DateField(blank=True, null=True, verbose_name='Выдача ключей')),
                ('middle_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средняя цена за 1 м2')),
                ('property_class', models.CharField(max_length=20, verbose_name='Класс недвижимости')),
                ('wall', models.CharField(max_length=20, verbose_name='Материал стен')),
                ('decoration', models.CharField(max_length=32, verbose_name='Тип отделки')),
                ('free_planning', models.CharField(max_length=10, verbose_name='Свободная планировка')),
                ('floors', models.PositiveSmallIntegerField(verbose_name='Количество этажей')),
                ('q_flats', models.PositiveSmallIntegerField(verbose_name='Количество квартир')),
                ('living_sq', models.PositiveIntegerField(verbose_name='Жилая площадь')),
                ('ceil_height', models.CharField(max_length=10, verbose_name='Высота потолков')),
                ('has_flats', models.BooleanField(default=False, verbose_name='Есть ли скрапер квартир')),
            ],
            options={
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32, verbose_name='город')),
                ('city_slug', models.SlugField(verbose_name='поле url')),
                ('city_code', models.PositiveSmallIntegerField(verbose_name='код города')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название ЖК')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='Адрес ЖК')),
                ('fk_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorerty', to='property.city', verbose_name='Для города')),
            ],
            options={
                'verbose_name_plural': 'Название ЖК для квартирограммы',
            },
        ),
        migrations.CreateModel(
            name='ObjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=64, verbose_name='Тип документа')),
                ('doc_date', models.DateTimeField(verbose_name='Дата размещения')),
                ('doc_link', models.URLField(verbose_name='ссылка на документ')),
                ('fk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.buildingobjects', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Документы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='MainPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to=property.models.img_path_photo, verbose_name='фото')),
                ('fk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_photos', to='property.buildingobjects', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Основные фото',
            },
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_num', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
                ('fl_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('fl_type', models.CharField(choices=[('C', 'студия'), ('1', '1 комнатная'), ('2', '2-х комнатная'), ('3', '3-х комнатная'), ('4', '4-х комнатная'), ('П', 'пентхаус')], max_length=10, verbose_name='Тип квартиры')),
                ('slug', models.SlugField(verbose_name='поле url')),
                ('fl_drawing', models.ImageField(blank=True, upload_to=property.models.img_path)),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('fl_decor', models.CharField(choices=[('Да', 'c отделкой'), ('Нет', 'без отделки'), ('-', 'нет данных'), ('whitebox', 'white box')], default='Нет', max_length=12, verbose_name='Отделка')),
                ('fl_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость квартиры')),
                ('fl_sq', models.FloatField(verbose_name='Площадь квартиры')),
                ('fl_status', models.CharField(choices=[('free', 'свободно'), ('reserved', 'забронировано'), ('sold', 'продано')], default='free', max_length=10, verbose_name='Статус квартиры')),
                ('fk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='property.property', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Квартирограмма',
            },
        ),
        migrations.CreateModel(
            name='CheckTermsPassKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.CharField(max_length=12, verbose_name='Первоначальная дата передачи квартир дольщикам')),
                ('changed_date', models.CharField(max_length=12, verbose_name='Планируемая дата передачи квартир дольщикам')),
                ('note', models.CharField(blank=True, max_length=32, verbose_name='Перенос сроков')),
                ('fk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_keys', to='property.buildingobjects', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Перенос сроков передачи ключей дольщикам',
            },
        ),
        migrations.CreateModel(
            name='CheckObjectReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness', models.CharField(max_length=5, verbose_name='Степень готовности')),
                ('initial_date', models.CharField(max_length=20, verbose_name='Срок в первой версии пр декларации')),
                ('changed_date', models.CharField(max_length=20, verbose_name='Срок в текущей версии пр декларации')),
                ('note', models.CharField(blank=True, max_length=32, verbose_name='Перенос сроков')),
                ('fk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_readiness', to='property.buildingobjects', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Перенос плановых сроков строительства',
            },
        ),
        migrations.CreateModel(
            name='BuildMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_month', models.CharField(max_length=20, verbose_name='Месяц строительства')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('fk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_months', to='property.buildingobjects', verbose_name='для объекта')),
            ],
            options={
                'verbose_name_plural': 'Фото объектов по месяцам стр-ва',
            },
        ),
        migrations.CreateModel(
            name='BuildingPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_img', models.ImageField(blank=True, upload_to=property.models.img_path_build)),
                ('fk_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_photos', to='property.buildmonths', verbose_name='месяц')),
            ],
            options={
                'verbose_name_plural': 'Фото строительства',
            },
        ),
        migrations.AddField(
            model_name='buildingobjects',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_objects', to='property.city'),
        ),
    ]
