# Generated by Django 4.0 on 2022-05-08 01:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='has_scraper',
            field=models.BooleanField(default=False, verbose_name='есть скрапер'),
        ),
        migrations.AddField(
            model_name='property',
            name='infr_desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Инфраструктура'),
        ),
        migrations.AddField(
            model_name='property',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='property',
            name='territory_desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Благоустройство'),
        ),
        migrations.AddField(
            model_name='property',
            name='work_desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Перечень работ'),
        ),
    ]
