# Generated by Django 4.0 on 2022-02-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_buildingobjects_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingobjects',
            name='build_stage',
            field=models.CharField(choices=[('b', 'строится'), ('p', 'сдан'), ('d', 'долгострой')], default='b', max_length=15, verbose_name='Стадия строительства'),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='ceil_height',
            field=models.CharField(max_length=15, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='free_planning',
            field=models.CharField(max_length=20, verbose_name='Свободная планировка'),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='property_class',
            field=models.CharField(max_length=32, verbose_name='Класс недвижимости'),
        ),
        migrations.AlterField(
            model_name='buildingobjects',
            name='wall',
            field=models.CharField(max_length=32, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='checkobjectreadiness',
            name='changed_date',
            field=models.CharField(max_length=32, verbose_name='Срок в текущей версии пр декларации'),
        ),
        migrations.AlterField(
            model_name='checkobjectreadiness',
            name='initial_date',
            field=models.CharField(max_length=32, verbose_name='Срок в первой версии пр декларации'),
        ),
        migrations.AlterField(
            model_name='checkobjectreadiness',
            name='note',
            field=models.CharField(blank=True, max_length=64, verbose_name='Перенос сроков'),
        ),
        migrations.AlterField(
            model_name='checkobjectreadiness',
            name='readiness',
            field=models.CharField(max_length=10, verbose_name='Степень готовности'),
        ),
        migrations.AlterField(
            model_name='checktermspasskeys',
            name='note',
            field=models.CharField(blank=True, max_length=64, verbose_name='Перенос сроков'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='fl_decor',
            field=models.CharField(choices=[('Да', 'c отделкой'), ('Нет', 'без отделки'), ('-', 'нет данных'), ('whitebox', 'white box')], default='Нет', max_length=32, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='fl_status',
            field=models.CharField(choices=[('free', 'свободно'), ('reserved', 'забронировано'), ('sold', 'продано')], default='free', max_length=20, verbose_name='Статус квартиры'),
        ),
        migrations.AlterField(
            model_name='flats',
            name='fl_type',
            field=models.CharField(choices=[('C', 'студия'), ('1', '1 комнатная'), ('2', '2-х комнатная'), ('3', '3-х комнатная'), ('4', '4-х комнатная'), ('П', 'пентхаус')], max_length=20, verbose_name='Тип квартиры'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес ЖК'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название ЖК'),
        ),
    ]
