# Generated by Django 4.0 on 2022-02-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_buildingobjects_build_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingobjects',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название ЖК'),
        ),
    ]
