# Generated by Django 4.0 on 2022-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_description_property_has_scraper_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildings',
            options={'ordering': ['middle_price', 'operation_term', 'num_dom'], 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='видеопрезентация'),
        ),
    ]
