# Generated by Django 4.0 on 2022-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_buildings_options_alter_property_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name_plural': 'ЖК комплексы'},
        ),
        migrations.AlterField(
            model_name='flats',
            name='fl_decor',
            field=models.CharField(choices=[('Да', 'c отделкой'), ('Нет', 'без отделки'), ('whitebox', 'white box'), ('zak', 'по желанию заказчика'), ('-', 'нет данных')], default='Нет', max_length=32, verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='property',
            name='buid_video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видеонаблюдение'),
        ),
    ]
