# Generated by Django 4.0 on 2022-06-12 07:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_options_alter_flats_fl_decor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.CharField(blank=True, choices=[('Да', 'c отделкой'), ('Нет', 'без отделки'), ('whitebox', 'white box'), ('zak', 'по желанию заказчика'), ('-', 'нет данных')], max_length=32, verbose_name='отделка')),
                ('decor_text', ckeditor.fields.RichTextField(blank=True, verbose_name='описание отделки квартир в ЖК')),
                ('fk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='property.property', verbose_name='для ЖК')),
            ],
            options={
                'verbose_name_plural': 'Отделка квартир в ЖК',
            },
        ),
        migrations.CreateModel(
            name='PropertyFloorPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=64, verbose_name='указание этажа/ей')),
                ('floor_drawing', models.ImageField(blank=True, null=True, upload_to=property.models.path_to_property, verbose_name='поэтажные планы квартир')),
                ('fk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='property.property', verbose_name='для ЖК')),
            ],
            options={
                'verbose_name_plural': 'Поэтажные планы квартир',
            },
        ),
        migrations.CreateModel(
            name='PropertyDecorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor_img', models.ImageField(blank=True, null=True, upload_to=property.models.path_to_property, verbose_name='картинка отделки ЖК')),
                ('fk_decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_images', to='property.propertydecor', verbose_name='для отделки')),
            ],
        ),
    ]
