# Generated by Django 4.0 on 2022-06-12 11:14

from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertydecor_propertyfloorplans_propertydecorimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydecorimages',
            options={'verbose_name_plural': 'Картинки отделки квартир в ЖК'},
        ),
        migrations.RemoveField(
            model_name='propertyfloorplans',
            name='fk_property',
        ),
        migrations.AddField(
            model_name='propertyfloorplans',
            name='fk_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='property.buildings', verbose_name='для дома ЖК'),
        ),
        migrations.AlterField(
            model_name='propertyfloorplans',
            name='floor_drawing',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.path_to_floor_plans, verbose_name='поэтажные планы квартир'),
        ),
    ]
