# Generated by Django 4.0 on 2022-06-21 10:28

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertydecorimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydecorimages',
            name='decor_img',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.path_to_decor, verbose_name='картинка отделки ЖК'),
        ),
    ]
