# Generated by Django 4.0 on 2022-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_infr_desc_alter_property_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, help_text='в конце адреса ?autoplay=1&mute=1, например: https://www.youtube.com/emded/hdi6vkQx?autoplay=1&mute=1', null=True, verbose_name='видеопрезентация'),
        ),
    ]
