# Generated by Django 4.0 on 2022-07-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_mediaflats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.URLField(max_length=250, verbose_name='фид с дом клик')),
                ('fk_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Фиды с дом.клик',
            },
        ),
    ]
