# Generated by Django 4.0 on 2022-07-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_propertyfeeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaflats',
            name='fk_property',
        ),
        migrations.AddField(
            model_name='mediaflats',
            name='fk_building',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='flats_media', to='property.buildings'),
            preserve_default=False,
        ),
    ]
