# Generated by Django 4.0 on 2022-07-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_mediaflats_fk_property_mediaflats_fk_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaflats',
            options={'ordering': ['fk_property'], 'verbose_name_plural': 'Медиаконтент квартир'},
        ),
        migrations.AlterModelOptions(
            name='propertyfeeds',
            options={'ordering': ['fk_property'], 'verbose_name_plural': 'Фиды с дом.клик'},
        ),
        migrations.RemoveField(
            model_name='mediaflats',
            name='fk_building',
        ),
        migrations.AddField(
            model_name='mediaflats',
            name='fk_property',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='flats_media', to='property.property'),
            preserve_default=False,
        ),
    ]
