# Generated by Django 4.0 on 2022-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mid_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='средний рейтинг новостройки'),
        ),
    ]
