# Generated by Django 4.0 on 2022-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_property_mid_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='описание для мета тэгов'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='key_words',
            field=models.CharField(blank=True, max_length=256, verbose_name='ключевые слова для мета тэгов'),
        ),
        migrations.AddField(
            model_name='flats',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='описание для мета тэгов'),
        ),
        migrations.AddField(
            model_name='flats',
            name='key_words',
            field=models.CharField(blank=True, max_length=256, verbose_name='ключевые слова для мета тэгов'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='описание для мета тэгов'),
        ),
        migrations.AddField(
            model_name='property',
            name='key_words',
            field=models.CharField(blank=True, max_length=256, verbose_name='ключевые слова для мета тэгов'),
        ),
    ]
